#!/usr/bin/env python3
"""
CIRRUS Action Extractor
Reads a digest file, uses Ollama to pull out action items, recommendations,
and CIRRUS improvement notes into a clean actions file.
"""

import json
import requests
from datetime import datetime
from pathlib import Path

# ── Config ──────────────────────────────────────────────────────────────────

CONFIG_PATH = Path.home() / "projects/cirrus-digest/config/sources.json"

with open(CONFIG_PATH) as f:
    CONFIG = json.load(f)

DIGEST_CFG  = CONFIG["digest"]
OUTPUT_DIR  = Path(DIGEST_CFG["output_dir"])
LOG_DIR     = Path(DIGEST_CFG["log_dir"])
MODEL       = DIGEST_CFG["ollama_model"]
OLLAMA_HOST = DIGEST_CFG["ollama_host"]

ACTIONS_DIR = OUTPUT_DIR / "actions"
ACTIONS_DIR.mkdir(parents=True, exist_ok=True)

# ── Helpers ──────────────────────────────────────────────────────────────────

def log(msg):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}")

def ollama_extract(prompt):
    try:
        resp = requests.post(
            f"{OLLAMA_HOST}/api/generate",
            json={"model": MODEL, "prompt": prompt, "stream": False,
                  "options": {"num_ctx": 8192}},
            timeout=120
        )
        resp.raise_for_status()
        return resp.json().get("response", "").strip()
    except Exception as e:
        return f"[Extraction error: {e}]"

# ── Extractor ────────────────────────────────────────────────────────────────

def extract_actions(digest_file: Path) -> Path:
    """Extract action items from a digest file and save to actions folder."""
    log(f"Extracting actions from: {digest_file.name}")

    content = digest_file.read_text()
    date_str = datetime.now().strftime("%Y-%m-%d")

    prompt = f"""You are CIRRUS, reviewing your own AI digest to extract actionable items.

Read the following digest and extract ALL of the following:

1. ACTION ITEMS — concrete tasks or next steps mentioned (e.g. install a tool, test a model, update a script)
2. RECOMMENDATIONS — suggestions for improving AI workflows, tools, or setups
3. CIRRUS IMPROVEMENT NOTES — anything tagged with "→ CIRRUS NOTE:" or suggestions for improving this digest system
4. INTERESTING TOOLS/MODELS — any new AI tools, models, or services worth investigating
5. FOLLOW-UP READING — articles, papers, or resources mentioned that are worth reading in full

Format your response as a clean markdown document with these 5 sections as headers.
For each item, include a one-line source reference (which newsletter/podcast it came from).
Be specific and actionable — skip vague observations.

DIGEST CONTENT:
{content[:6000]}

Output the action items document now:"""

    extracted = ollama_extract(prompt)

    # Determine prefix (daily vs weekly)
    prefix = "daily-actions" if digest_file.name.startswith("daily") else "weekly-actions"
    actions_file = ACTIONS_DIR / f"{prefix}-{date_str}.md"

    with open(actions_file, "w") as f:
        f.write(f"# CIRRUS Action Items — {date_str}\n")
        f.write(f"*Extracted from: {digest_file.name}*\n\n")
        f.write("---\n\n")
        f.write(extracted)
        f.write(f"\n\n---\n*Generated by CIRRUS using `{MODEL}`*\n")

    log(f"Actions saved: {actions_file}")
    return actions_file


def extract_from_latest(prefix="digest"):
    """Find the most recent digest file and extract actions from it."""
    files = sorted(OUTPUT_DIR.glob(f"{prefix}-*.md"), reverse=True)
    if not files:
        log(f"No {prefix} files found in {OUTPUT_DIR}")
        return None
    return extract_actions(files[0])


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        extract_actions(Path(sys.argv[1]))
    else:
        # Default: extract from latest weekly digest
        extract_from_latest("digest")
