#!/bin/bash
# oneshot_timeouts.sh — S96, 2026-09-02. Bound every oneshot job unit so a hang
# ends as a FAILURE instead of running forever with nothing reporting it.
#
# WHY THIS EXISTS
# ---------------
# On the morning of 2026-09-02 two scheduled jobs were found hung on a socket
# that never timed out, and nothing anywhere said so:
#
#   CIRRUS   cirrus_daily     PID 12208    6h47m elapsed, ~0 CPU, one ESTABLISHED socket
#   CUMULUS  pedagogy_daily   PID 1597383  2h47m elapsed, 279ms CPU  (Alyssa's digest)
#
# Neither crashed. Neither logged an error. Both simply never finished, so
# neither ever called job_status.record() — and a job that never records looks
# exactly like a job nobody asked about.
#
# WHY SYSTEMD LET IT HAPPEN
# -------------------------
# For Type=oneshot, TimeoutStartSec defaults to **infinity** — NOT to
# DefaultTimeoutStartSec. That is measured here, not taken from the manual:
# cirrus-pedagogy.service sat in `activating (start)` for 2h47m, which the usual
# 90s default would have ended at 06:01:35. Every oneshot job on the box was
# free to hang forever.
#
# WHY A DROP-IN AND NOT AN EDIT TO THE UNIT
# -----------------------------------------
# Most of these unit files exist ONLY on the box, not in the repo; the few that
# are in the repo get overwritten by the next deploy, so a fix written into them
# would silently revert — the exact class of failure this tree keeps paying for.
# A drop-in survives a deploy, covers units the repo has never seen, and is
# undone by deleting one directory.
#
# THE CEILING IS MEASURED, NOT GUESSED
# ------------------------------------
# From `runner job-durations` the same morning: hoaleads 4m01s, billsnow 3m01s,
# pedagogy 1m00s–2m37s, modelhealth 10s, billnewdev 1s. 30 minutes is roughly
# 10x the worst real run — far above anything normal, far below "nobody noticed
# until tomorrow."
#
# SAFETY RULES THIS SCRIPT OBEYS
# ------------------------------
#   * Type=oneshot ONLY. A long-lived Type=simple daemon (cirrus-api, the bot,
#     the tunnel) must never be capped — capping one would restart-loop a
#     healthy service, which is a worse outage than the bug being fixed.
#   * Our namespaces only. Never a distro or vendor unit.
#   * A unit that already sets its own TimeoutStartSec is LEFT ALONE and named
#     in the output. halftime-routing deliberately uses 4h because it is a long
#     sweep; silently capping it at 30m would break a working job.
#   * dry-run is the DEFAULT. `live` is explicit.
#
# Usage:  oneshot_timeouts.sh [dry-run|live] [seconds]
# Exit 0 = reported (dry-run) or applied (live).
set -uo pipefail

MODE="${1:-dry-run}"
SEC="${2:-1800}"

case "$MODE" in
    dry-run|live) ;;
    *) echo "REFUSED: mode must be 'dry-run' or 'live' (got '$MODE')"; exit 2 ;;
esac
if ! printf '%s' "$SEC" | grep -qE '^[0-9]{2,5}$'; then
    echo "REFUSED: seconds must be 2-5 digits (got '$SEC')"; exit 2
fi

ours() {
    case "$1" in
        cirrus-*|alopecia-*|halftime-*|opportunity-*|cumulus-*|entity-kb-*) return 0 ;;
        *) return 1 ;;
    esac
}

CHANGED=0
SKIPPED_OWN=0
echo "== oneshot job units (mode=$MODE, ceiling=${SEC}s) =="

while read -r U _rest; do
    [ -n "$U" ] || continue
    ours "$U" || continue
    [ "$(systemctl show "$U" -p Type --value 2>/dev/null)" = oneshot ] || continue

    CUR=$(systemctl show "$U" -p TimeoutStartUSec --value 2>/dev/null)
    if [ "$CUR" != infinity ]; then
        # Already bounded — either by the unit itself or by a previous run of
        # this script. Either way, do not touch it.
        printf '  %-42s already bounded (%s)\n' "$U" "$CUR"
        SKIPPED_OWN=$((SKIPPED_OWN + 1))
        continue
    fi

    printf '  %-42s UNBOUNDED -> %ss\n' "$U" "$SEC"
    if [ "$MODE" = live ]; then
        D="/etc/systemd/system/$U.d"
        sudo mkdir -p "$D" || { echo "    !! mkdir failed for $D"; exit 3; }
        sudo tee "$D/90-timeout.conf" >/dev/null <<EOF
# S96 (2026-09-02): Type=oneshot defaults to TimeoutStartSec=infinity, so a hung
# job runs forever and never records a result. Two jobs hung for hours on
# 2026-09-02 with nothing reporting it. Generated by oneshot_timeouts.sh.
[Service]
TimeoutStartSec=$SEC
EOF
        CHANGED=$((CHANGED + 1))
    fi
done < <(systemctl list-unit-files --type=service --no-legend 2>/dev/null)

if [ "$MODE" = live ] && [ "$CHANGED" -gt 0 ]; then
    sudo systemctl daemon-reload || { echo "!! daemon-reload FAILED"; exit 4; }
    echo
    echo "== after: effective TimeoutStartUSec (this is the check, not the write) =="
    BAD=0
    while read -r U _rest; do
        [ -n "$U" ] || continue
        ours "$U" || continue
        [ "$(systemctl show "$U" -p Type --value 2>/dev/null)" = oneshot ] || continue
        EFF=$(systemctl show "$U" -p TimeoutStartUSec --value 2>/dev/null)
        printf '  %-42s %s\n' "$U" "$EFF"
        [ "$EFF" = infinity ] && BAD=$((BAD + 1))
    done < <(systemctl list-unit-files --type=service --no-legend 2>/dev/null)
    echo
    echo "applied: $CHANGED   left alone (already bounded): $SKIPPED_OWN"
    if [ "$BAD" -gt 0 ]; then
        echo "!! $BAD oneshot unit(s) STILL infinity after the write — not a clean result."
        exit 5
    fi
    echo "OK — no oneshot job unit is unbounded."
elif [ "$MODE" != live ]; then
    echo
    echo "(dry-run — nothing written. Re-run with mode=live to apply.)"
else
    echo
    echo "nothing to change; $SKIPPED_OWN unit(s) already bounded."
fi
